name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branchName:
        description: "Name of the branch to build"
        required: true
        default: "main"
jobs:
  build:
    name: Lint and build the apkt on push to master
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branchName }}
    - run: git checkout $branchName
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Lint the project
      run: ./gradlew ktlintCheck
    - name: Run unit tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
